### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: redditdownload/index.html

### ISSUE THREAD

**Issue by a1270** [rachmadaniHaryono/RedditImageGrab#10]
I am using bash on windows ubuntu version. I pull down the repo from github and do the following:
>$ pip install .
>$ pip install .[server]

Running the server like this:
>$ redditdl-server run -p 5004 --with-threads

Here is a gist of the error: https://gist.github.com/a1270/ecaab7ab22ba11098ffb3dc032dce7d7

Any ideas? thank you.

**Comment by rachmadaniHaryono** [comment]
can go into the folder ( `cd redditdownload`) and run the command?

you should be in the same folder as `setup.py`

e: some update just already uploaded, you may want to fetch that

**Comment by a1270** [comment]
>$ cd RedditImageGrab/redditdownload/
>$ redditdl-server run -p 5004 --with-threads

Same error as gist above. Same goes being in the base dir with setup.py.

**Comment by rachmadaniHaryono** [comment]
try `pip install -e . && pip install install -e .[server]`. 

also the recent commit didn't include flask-debugtoolbar which may raise error. if it happen just install it `pip install flask-debugtoolbar`

it seems the setup.py don't include the html file (should be fixed on next commit)

e: fixed on 68c17edea8cc4a5fc1e91100b5ef3c758ffe4642

**Comment by a1270** [comment]
I'll just add I did 
>sudo pip install https://github.com/rachmadaniHaryono/RedditImageGrab/archive/master.zip

and it seems to be working when I visit 127.0.0.1:5004 also lacks errors in the terminal.

thank you. I close the issue.

**Comment by rachmadaniHaryono** [comment]
just recommendation: it is not recommended to run sudo under pip https://stackoverflow.com/questions/15028648/is-it-acceptable-and-safe-to-run-pip-install-under-sudo
