### ISSUE TITLE
fix processing imgur url

### ISSUE THREAD

**Issue by rachmadaniHaryono** [rachmadaniHaryono/RedditImageGrab#6]
this url http://imgur.com/aClb5Mp dont have extension and by defult will downloaded as jpg image. In fact this is gif image (~50mb). there must be a way to check if imgur contain mp4 or webm link on the page

**Comment by MichaelHunt666** [comment]
#!/bin/bash

for f in *; do 
    type=$( file "$f" | grep -oP '\w+(?= image data)' )
    case $type in  
        PNG)  newext=png ;; 
        GIF)  newext=gif ;; 
        JPEG) newext=jpg ;; 
        *)    continue ;; 
#        *)    echo "what is this: $f"; continue ;; 
    esac
    ext=${f##*.}   # remove everything up to and including the last dot
    if [[ $ext != $newext ]]; then
        # remove "echo" if you're satisfied it's working
        echo renaming "$f" "${f%.*}.$newext"
        mv "$f" "${f%.*}.$newext"
    fi
done

**Comment by rachmadaniHaryono** [comment]
i believe this fix the file after downloading and i hope the fix can recognize it before download. other solution that i can find is to use file from another project
